name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: kintull/gpanel_one_page

  GPANEL_HOST: ${{secrets.HOST}}
  GPANEL_INTERNAL_PORT: ${{secrets.INTERNAL_PORT}}
  GPANEL_EXTERNAL_PORT: ${{secrets.EXTERNAL_PORT}}
  GPANEL_SSL_CERT_PATH: ${{secrets.SSL_CERT_PATH}}
  GPANEL_SSL_KEY_PATH: ${{secrets.SSL_KEY_PATH}}
  DOCKER_LOGIN: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: make build-prod

      - name: Log into registry
        run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD

      - name: Push image
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_NAME
          echo VERSION=$VERSION

          docker push $IMAGE_NAME:$VERSION
